# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pagepal_development
  username: dell # <-- Replace 'dell' with your Ubuntu username if it's different

test:
  <<: *default
  database: pagepal_test
  username: dell # <-- Replace 'dell' with your Ubuntu username if it's different

production:
  <<: *default
  database: pagepal_production
  username: <%= ENV["RAILS_DB_USERNAME"] %>
  password: <%= ENV["RAILS_DB_PASSWORD"] %>
  host: <%= ENV["RAILS_DB_HOST"] %>
  port: <%= ENV["RAILS_DB_PORT"] %>
  # The `url` key is often used by deployment platforms like Render/Fly.io
  # that provide a full DATABASE_URL environment variable.
  # url: <%= ENV["DATABASE_URL"] %>